### PR TITLE
update cats to 0.4.0 release

### PR DESCRIPTION
**Pull request by crispywalrus**
Having found this a valuable library and ready to speed my compile up by moving to 0.4.0 release of cats I took the quick step of doing that for catbird. Beyond the version bump there are a couple of very minor fixes. First replace Kleisli.function with apply. Secondly change order of parameters to ap in futureInstance.

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, @crispywalrus!

**Comment by crispywalrus** [comment]
Wow! great turnaround time, thanks. could I get you to publish a new release version 0.1.1 or some such?

**Comment by travisbrown** [comment]
@crispywalrus Is an update to Bijection 0.9.0 okay with you? I'll go ahead and publish 0.2.0 after #10 gets merged.

**Comment by crispywalrus** [comment]
updating bijections is fine by me

**Pull request merged**
