### PR TITLE
Bracket instance for Future.

### PR DESCRIPTION
**Pull request by dangerousben**

### CODE REVIEW

**Comment by dangerousben** [comment]
Huh... the build was failing and I tweaked the travis config a bit (updating versions and fixing warnings), not expecting that to fix it, but now it passes.  So possibly an intermittent failure lurking here.

**Comment by dangerousben** [comment]
> Huh... the build was failing and I tweaked the travis config a bit (updating versions and fixing warnings), not expecting that to fix it, but now it passes. So possibly an intermittent failure lurking here.

Scratch that, the failure was actually due to a scalafmt error, fixed now.

**Comment by travisbrown** [comment]
@felixbr Any objection to merging this before a new release?

**Comment by felixbr** [comment]
No, looks great! 👍

**Pull request merged**
